### ISSUE TITLE
Can't get it working in any usable fashion.

### ISSUE THREAD

**Issue by rileyrg** [zonuexe/psysh.el#7]
`(setq psysh-comint-buffer-process "path/to/shell.php")`

I pointed it to a copy of shell.php and it complains that:-

> Wrong type argument: listp, "path/to/shell.php"

Not setting it and running psysh inside emacs I get

> WARNING: terminal is not fully functional

The second part is down to using `less ` I think but using `(setenv "PAGER" "cat")` doesn't cure it either.

A usage example would be great.  How is psysh supposed to launch? When my webserver hits the Psy/Shell line the webserver running in the terminal shws Psy output  - a manually started PsySh "shell" in emacs sits there.

**Comment by frankgerhardt** [comment]
Oh, posted Dec 30th, just recently. Hmm, one year ago. No answer!? 

I got it work somehow. I don't use `shell.php` and I leave the variable `psysh-comint-buffer-process` unset. `psysh` is installed with composer and the `bin` directory where it was downloaded is on my PATH. 

![tty](https://user-images.githubusercontent.com/550621/103433033-4fe88100-4bea-11eb-948d-23414b5c98d1.gif)

Then Invoke `M-x psysh` and it will open it in a second buffer that is totally unrelated to the PHP file. In the PHP  file buffer select a region and invoke `M-x psysh-eval-region`. I could not find a keybinding for it. The `php-mode` seems to be rather unaffected by `psysh-mode` running in the other buffer.

**Comment by rileyrg** [comment]
> Oh, posted Dec 30th, just recently. Hmm, one year ago. No answer!?
> 
> I got it work somehow. I don't use `shell.php` and I leave the variable `psysh-comint-buffer-process` unset. `psysh` is installed with composer and the `bin` directory where it was downloaded is on my PATH.
> 
> ![tty](https://user-images.githubusercontent.com/550621/103433033-4fe88100-4bea-11eb-948d-23414b5c98d1.gif)
> 
> Then Invoke `M-x psysh` and it will open it in a second buffer that is totally unrelated to the PHP file. In the PHP file buffer select a region and invoke `M-x psysh-eval-region`. I could not find a keybinding for it. The `php-mode` seems to be rather unaffected by `psysh-mode` running in the other buffer.

Heh. Blast from the past. I didn't follow it up. Moved on. I'll close it.
